#카테고리별 도서 판매량 집계하기
SELECT
    BOOK.CATEGORY,
    SUM(BOOK_SALES.SALES) as TOTAL_SALES
FROM BOOK 
INNER JOIN BOOK_SALES
    on BOOK.BOOK_ID = BOOK_SALES.BOOK_ID
WHERE SALES_DATE like '2022-01%'
GROUP BY CATEGORY
ORDER BY CATEGORY 
